version: '3.8'

services:
  backend:
    container_name: springboot-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_TOOL_OPTIONS=-Xmx512m -Xms256m
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: unless-stopped
    stdin_open: true
    tty: true
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge