services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
      - ~/.m2:/root/.m2
    command: mvn spring-boot:run
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - JAVA_TOOL_OPTIONS=-Xmx512m -Xms256m
    working_dir: /app

  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /app
    stdin_open: true
    tty: true