### list Estimate
GET http://localhost:8080/api/estimates

### Create Estimate Test
POST http://localhost:8080/api/estimates
Content-Type: application/json

{
  "id": 359,
  "title": null,
  "cityName": "10",
  "placeName": "Test",
  "structureType": "AT",
  "width": 11,
  "length": 11,
  "height": 11,
  "trussHeight": 1,
  "eavesLength": 0,
  "rearTrussHeight": 0,
  "insideWidth": 0,
  "insideLength": 0,
  "rooftopSideHeight": 0,
  "rooftopWidth": 0,
  "rooftopHeight": 0,
  "rooftopLength": 0,
  "createdAt": "2025-06-02T21:25:51.407134",
  "updatedAt": "2025-06-02T21:25:51.407134",
  "structureDetail": {
    "insideWallYn": "Y",
    "ceilingYn": "Y",
    "windowYn": "Y",
    "doorYn": "Y",
    "canopyYn": "Y",
    "downpipeYn": "N",
    "insideWallType": "E",
    "insideWallPaper": "E1",
    "insideWallThick": 75,
    "outsideWallType": "E",
    "outsideWallPaper": "E1",
    "outsideWallThick": 75,
    "roofType": "W",
    "roofPaper": "W1",
    "roofThick": 75,
    "ceilingType": "G",
    "ceilingPaper": "G1",
    "ceilingThick": 75,
    "gucci": 100,
    "gucciInside": null,
    "gucciInsideAmount": null,
    "gucciAmount": 1,
    "canopyList": [
      {
        "id": 366,
        "length": 11,
        "amount": 1,
        "width": 0,
        "height": 0,
        "type": null,
        "subType": null,
        "selectWh": null
      }
    ],
    "ceilingList": [
      {
        "id": 354,
        "length": 11,
        "amount": 1,
        "width": 0,
        "height": 1,
        "type": null,
        "subType": null,
        "selectWh": null
      }
    ],
    "doorList": [
      {
        "id": 354,
        "length": 0,
        "amount": 1,
        "width": 11,
        "height": 111,
        "type": "O",
        "subType": "S",
        "selectWh": null
      }
    ],
    "downpipeList": [],
    "insideWallList": [
      {
        "id": 355,
        "length": 11,
        "amount": 1,
        "width": 0,
        "height": 1,
        "type": null,
        "subType": null,
        "selectWh": null
      }
    ],
    "windowList": [
      {
        "id": 354,
        "length": 0,
        "amount": 1,
        "width": 11,
        "height": 1,
        "type": "D",
        "subType": null,
        "selectWh": null
      },
      {
        "id": 355,
        "length": 0,
        "amount": 2,
        "width": 22,
        "height": 2,
        "type": "S",
        "subType": null,
        "selectWh": null
      }
    ]
  }
}

### UPDATE Estimate
PUT http://localhost:8080/api/estimates/1
Content-Type: application/json

{
  "title": "Updated Title",
  "cityName": "10",
  "placeName": "Updated Location",
  "structureType": "AG",
  "width": 6000,
  "length": 10000,
  "height": 3000,
  "trussHeight": 1500,
  "eavesLength": 600,
  "rearTrussHeight": 1400,
  "insideWidth": 5800,
  "insideLength": 9800,
  "rooftopSideHeight": 0,
  "rooftopWidth": 0,
  "rooftopLength": 0,
  "rooftopHeight": 0,
  "insideWallYn": "Y",
  "ceilingYn": "Y",
  "windowYn": "Y",
  "doorYn": "Y",
  "canopyYn": "Y",
  "downpipeYn": "N",
  "insideWallType": "E",
  "insideWallPaper": "E1",
  "insideWallThick": 75,
  "outsideWallType": "E",
  "outsideWallPaper": "E1",
  "outsideWallThick": 75,
  "roofType": "E",
  "roofPaper": "E1",
  "roofThick": 75,
  "ceilingType": "E",
  "ceilingPaper": "E1",
  "canopyList": [],
  "ceilingList": [],
  "doorList": [],
  "downpipeList": [],
  "insideWallList": [],
  "windowList": [],
  "calculateList": []
}

### Update Estimate
PUT http://localhost:8080/api/estimates/1102
Content-Type: application/json

{
  "title": "업데이트된 견적서 111",
  "cityName": "SEOUL",
  "placeName": "서울 강남구",
  "structureType": "AG",
  "width": 6000,
  "length": 10000,
  "height": 3000,
  "trussHeight": 1500,
  "eavesLength": 500,
  "rearTrussHeight": 1300,
  "insideWidth": 5800,
  "insideLength": 9800,
  "rooftopSideHeight": 0,
  "rooftopWidth": 0,
  "rooftopLength": 0,
  "rooftopHeight": 0,

  "insideWallYn": "Y",
  "ceilingYn": "Y",
  "windowYn": "Y",
  "doorYn": "Y",
  "canopyYn": "Y",
  "downpipeYn": "Y",

  "insideWallType": "E",
  "insideWallPaper": "E1",
  "insideWallThick": 75,
  "outsideWallType": "E",
  "outsideWallPaper": "E1",
  "outsideWallThick": 75,
  "roofType": "E",
  "roofPaper": "E1",
  "roofThick": 75,
  "ceilingType": "E",
  "ceilingPaper": "E1",

  "canopyList": [
    { "length": 2000, "amount": 20 }
  ],
  "ceilingList": [
    { "length": 3000, "height": 2500, "amount": 20 }
  ],
  "doorList": [
    { "width": 900, "height": 2100, "amount": 20, "type": "O", "subType": "S" }
  ],
  "downpipeList": [
    { "width": 200, "height": 3000, "amount": 20}
  ],
  "insideWallList": [
    { "length": 5000, "height": 2500, "amount": 20 }
  ],
  "windowList": [
    { "width": 1200, "height": 1000, "amount": 20, "type": "S" }
  ]
}

### DELETE Estimate
DELETE http://localhost:8080/api/estimates/1102