spring:
  sql:
    init:
      mode: never

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: m2jungjin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          prepare_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom application properties
app:
  upload:
    dir: /Users/riayu/IdeaProjects/m2/backend/src/main/webapp/upload

cors:
  allowed-origins: https://m2-v2.vercel.app