spring:
  devtools:
    livereload:
      enabled: true

  freemarker:
    cache: false

  datasource:
    url: jdbc:postgresql://localhost:5432/m2
    username: riayu
    password: ""
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  h2:
    console:
      enabled: true
      path: /h2-console

# Custom application properties
file:
  upload-dir: /Users/rosariayu/IdeaProjects/m2/src/main/webapp/upload