spring:
  datasource:
    url: jdbc:postgresql://db.qibjhketqjmupgdisash.supabase.co:5432/postgres
    username: postgres
    password: m2jungjin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Custom application properties
app:
  upload:
    dir: /Users/riayu/IdeaProjects/m2/backend/src/main/webapp/upload

cors:
  allowed-origins: http://localhost:3000